### ISSUE TITLE
Localhost HTTPS Cert

### ISSUE THREAD

**Issue by DroopyTersen** [pschaeflein/spfx-codespaces#1]
Thank you for the blog post on setting up SPFx in Codespaces. Following your instructions I was able to get everything up an running. This combined with Github Actions could yield some really exciting things for SPFx developers! 

However, I can't figure out how to setup the Self Signed Dev certificate.  I tried running `gulp trust-dev-cert` from the VS Code terminal once the Codespace was loaded. It worked without error, but doesn't seem to have done anything.  

How did you get past this to load your session in Workbench?

![image](https://user-images.githubusercontent.com/4020046/83300963-81195280-a1be-11ea-8f74-58f53a053bc1.png)

![image](https://user-images.githubusercontent.com/4020046/83302180-79f34400-a1c0-11ea-99e4-157aec75cf2a.png)

**Comment by pschaeflein** [comment]
The browser is not in the codespace, so run the trust-dev-cert on your local machine.

**Comment by DroopyTersen** [comment]
I've already run it locally for other projects, and don't have an issue on locally hosted SPFx projects. Would it still make sense that I need to run it then? Or is there a mismatch between certs maybe?  

I was able to get it working by running `gulp trust-dev-cert` in the Codespace, then following [these instructions](https://peacocksoftware.com/blog/make-chrome-auto-accept-your-self-signed-certificate) to manually trust the certificate on my local machine.  Just seems like I'm overlooking something simpler.

**Comment by pschaeflein** [comment]
I've figured out an easier way (at least to me). Running `gulp trust-dev-cert` in the VS Code terminal (which is on the Codespace container) will create the .cer file in **/home/vsonline/.gcb-serve-data folder**.

Add that folder to the workspace, and you will then see the .cer file in the VSCode explorer window. From there, right-click and select download (or drag/drop) to get it on your local computer. Then import to Trusted Root Certification Authorities.

I'm working on a document to spell this out.

Thanks!

**Comment by pschaeflein** [comment]
https://www.schaeflein.net/spfx-in-codespaces-trust-the-dev-cert/
